export const Product = [
    {
        productID: 'P001',
        pro_name: 'shoes1',
        catagory: 'Man',
        brand: 'Adibas',
        avaliable: 1,
        size: 'UK35',
    },
    {   
        productID: 'P002',
        pro_name: 'shoes2',
        catagory: 'Women',
        brand: 'Nike',
        avaliable: 0,
        size: 'UK36',
    },
    {
        productID: 'P003',
        pro_name: 'shoes3',
        catagory: 'Kid',
        brand: 'Aria',
        avaliable: 1,
        size: 'UK35',
    },
    {
        productID: 'P003',
        pro_name: 'shoes3',
        catagory: 'Kid',
        brand: 'Aria',
        avaliable: 1,
        size: 'UK35',
    },
    {
        productID: 'P003',
        pro_name: 'shoes3',
        catagory: 'Kid',
        brand: 'Aria',
        avaliable: 1,
        size: 'UK35',
    },
    {
        productID: 'P003',
        pro_name: 'shoes3',
        catagory: 'Kid',
        brand: 'Aria',
        avaliable: 1,
        size: 'UK35',
    },
    
];